# build artifacts
build/
dist/

# ide support (in general)
.env*
!.env.sample
!.envrc
/.idea/
/.vscode/*
!/.vscode/*.sample.json
!/.vscode/*.sample

# Ignore all logfiles and tempfiles.
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
log/
!/log/.keep

# Temporary files
tmp/
!/tmp/.keep

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# Dependency directories
node_modules/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# Serverless directories
.serverless/

# miscellaneous
.DS_Store
